apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  labels:
    app: redis-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
        - name: service
          image: redis:alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          env:
            - name: DISABLE_PROFILER
              value: "1"
            - name: DISABLE_TRACKING
              value: "1"
          livenessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          readinessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          resources:
            requests:
              cpu: 70m
              memory: 200Mi
            limits:
              cpu: 140m
              memory: 300Mi
      volumes:
        - name: redis-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379 